-- NYCE Card Alert Interface - Oracle Database Schema

-- Fraud Alert Tables
CREATE TABLE FRAUD_ALERT (
    ALERT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSACTION_ID VARCHAR2(50) NOT NULL,
    CARD_NUMBER VARCHAR2(16) NOT NULL,
    MERCHANT_NAME VARCHAR2(100),
    AMOUNT NUMBER(12,2),
    ALERT_TYPE VARCHAR2(30),
    RISK_SCORE NUMBER(5,2),
    ALERT_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR2(20) DEFAULT 'NEW'
);

CREATE TABLE FRAUD_CARD_BLOCK_REISSUE (
    BLOCK_REISSUE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CARD_NUMBER VARCHAR2(16) NOT NULL,
    BLOCK_REASON VARCHAR2(255),
    BLOCK_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NEW_CARD_NUMBER VARCHAR2(16),
    REISSUE_STATUS VARCHAR2(20) DEFAULT 'PENDING'
);

CREATE TABLE FRAUD_CARD_SUSPECT_TRAN (
    SUSPECT_TRAN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TRANSACTION_ID VARCHAR2(50) NOT NULL,
    CARD_NUMBER VARCHAR2(16) NOT NULL,
    MERCHANT_CODE VARCHAR2(10),
    TRANSACTION_AMOUNT NUMBER(12,2),
    TRANSACTION_TIMESTAMP TIMESTAMP,
    SUSPECT_REASON VARCHAR2(255)
);

-- Case Management Tables
CREATE TABLE CS_CASE (
    CASE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ALERT_ID NUMBER,
    CUSTOMER_ID VARCHAR2(50),
    CREATED_BY VARCHAR2(50) DEFAULT 'SYSTEM',
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_TIMESTAMP TIMESTAMP,
    CASE_RISK_SCORE NUMBER(5,2),
    FOREIGN KEY (ALERT_ID) REFERENCES FRAUD_ALERT(ALERT_ID)
);

CREATE TABLE CS_CASE_STATUS (
    CASE_ID NUMBER,
    STATUS VARCHAR2(30) DEFAULT 'OPEN',
    STATUS_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ANALYST_NAME VARCHAR2(100),
    COMMENTS VARCHAR2(500),
    PRIMARY KEY (CASE_ID, STATUS_TIMESTAMP),
    FOREIGN KEY (CASE_ID) REFERENCES CS_CASE(CASE_ID)
);

CREATE TABLE CS_CASE_ACTION (
    ACTION_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CASE_ID NUMBER,
    ACTION_TYPE VARCHAR2(50),
    ACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTION_BY VARCHAR2(50),
    ACTION_DETAILS VARCHAR2(500),
    FOREIGN KEY (CASE_ID) REFERENCES CS_CASE(CASE_ID)
);

-- Hotlist Tables
CREATE TABLE FRAUD_HOTLIST (
    HOTLIST_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CARD_NUMBER VARCHAR2(16) NOT NULL UNIQUE,
    BLOCK_REASON VARCHAR2(255),
    BLOCK_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRATION_TIMESTAMP TIMESTAMP
);

-- Indexes for Performance
CREATE INDEX IDX_FRAUD_ALERT_CARD ON FRAUD_ALERT(CARD_NUMBER);
CREATE INDEX IDX_FRAUD_ALERT_TIMESTAMP ON FRAUD_ALERT(ALERT_TIMESTAMP);
CREATE INDEX IDX_CS_CASE_STATUS ON CS_CASE_STATUS(STATUS);
CREATE INDEX IDX_FRAUD_HOTLIST_CARD ON FRAUD_HOTLIST(CARD_NUMBER);